name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.11', '1.12']
    runs-on: ${{ matrix.os }}
    name: Test Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v1
      - run: go test ./...
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - uses: actions/checkout@v1
      - run: go test github.com/pelletier/go-toml -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
        secrets: ["CODECOV_TOKEN"]
