name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.11', '1.12']
    runs-on: ${{ matrix.os }}
    name: Test Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v1
      - run: go test ./...
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - uses: actions/checkout@v1
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  fmt:
    name: Go fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - uses: actions/checkout@v1
      - run: go fmt ./...
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - uses: actions/checkout@v1
      - run: echo '##[add-path]/home/runner/go/bin'
      - run: ./benchmark.sh master https://github.com/$GITHUB_REPOSITORY.git

  fuzzing:
    name: Run fuzzing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12'
      - uses: actions/checkout@v1
      - run: echo '##[add-path]/home/runner/go/bin'
      - run: ./fuzzit.sh
        env:
          TYPE: local-regression
