name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: ['1.11', '1.12']
    runs-on: ${{ matrix.os }}
    name: Test Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v1
    - run: go test ./...
